# delta_hedger/config.py

import os
from dotenv import load_dotenv

# --- Load Environment Variables ---
load_dotenv(override=True)

# Alpaca API credentials and trading mode.
# IS_PAPER_TRADING should be True for testing in a paper environment.
IS_PAPER_TRADING = os.getenv("IS_PAPER_TRADING", "true").lower() == "true"
API_KEY = os.getenv("TRADING_API_KEY")
API_SECRET = os.getenv("TRADING_API_SECRET")


# --- Strategy & Ticker Configuration ---
# The underlying asset for the gamma scalping strategy.
# This is the stock or ETF you want to trade.
HEDGING_ASSET = "TSLA"
# The directory where trade execution logs will be stored.
TRADE_LOG_DIR = "trades"
# --- Initialization Mode ---
# 'init': The application will liquidate any existing positions for the HEDGING_ASSET
#         and its options, then establish a new straddle to start fresh.
# 'resume': The application will assume a straddle is already in place and will
#           sync with the existing positions to begin hedging immediately.
INITIALIZATION_MODE = "init"


# --- Hedging Strategy Parameters ---
# The 'dead band' for our portfolio's net delta. A hedge trade is triggered
# if the absolute value of the net delta exceeds this threshold. A larger value
# means fewer, larger trades, while a smaller value results in more frequent,
# smaller adjustments. Finding the right balance is key to profitability.
HEDGING_DELTA_THRESHOLD = 2.0  # e.g., re-hedge when delta moves by +/- 2 shares
# The number of straddles (1 call + 1 put) to purchase. This is the primary
# lever for scaling the overall size of the strategy. All subsequent hedge
# trades will be scaled based on this multiplier.
STRATEGY_MULTIPLIER = 1
# The ideal time-to-expiration for the options contracts. The strategy will
# search for contracts within this window.
# A longer time to expiration means lower time decay (theta) but also lower gamma.
MIN_EXPIRATION_DAYS = 30
# A shorter time to expiration means higher gamma (good) but also higher theta (bad).
MAX_EXPIRATION_DAYS = 90
# A filter to ensure we only trade options with sufficient liquidity.
# Higher open interest generally means tighter bid-ask spreads and better execution.
MIN_OPEN_INTEREST = 100
# A weighting factor for theta in the straddle selection score.
# This determined the importance of time decay (the cost of holding) 
# relative to execution costs (the cost of entering the position).
# It should be roughly equal to the number of days you intend to run the scalp.
THETA_WEIGHT = 1.0 
# A fallback risk-free interest rate used for options pricing models if the live
# rate cannot be fetched from the US Treasury yield curve.
DEFAULT_RISK_FREE_RATE = 0.05


# --- Market State Trigger Parameters ---
# Defines how sensitive the system is to market data for triggering a delta recalculation.
# A new delta calculation is triggered if the underlying asset's price moves by this amount.
PRICE_CHANGE_THRESHOLD = 0.05  # In dollars
# In a quiet market, a delta recalculation is triggered at this fixed interval.
HEARTBEAT_TRIGGER_SECONDS = 5.0


# --- Position Manager Parameters ---
# A safety mechanism. If a trade command generated by the strategy is not
# processed by the Position Manager within this time frame, it is considered
# stale and discarded. This prevents the execution of outdated trades.
TRADE_COMMAND_TTL_SECONDS = 5.0

# Standard number of shares represented by one options contract.
OPTIONS_CONTRACT_MULTIPLIER = 100

# --- Logging Configuration ---
# Configures the format and level for application-wide logging.
LOG_FORMAT = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
LOG_LEVEL = "INFO"
